services:
    # backend: Laravel (PHP-FPM)
    app:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        container_name: ticketing-app
        working_dir: /var/www
        volumes:
            - ./backend:/var/www
        env_file:
            - ./backend/.env.docker
        networks:
            - ticketing
        depends_on:
            - mysql

    # frontend: React + Vite
    frontend:
        build:
            context: ./frontend
            dockerfile: ../docker/frontend/Dockerfile
        container_name: ticketing-frontend
        volumes:
            - ./frontend:/app
            - node_modules:/app/node_modules
        ports:
            - "5173:5173"
        networks:
            - ticketing
        depends_on:
            - app

    # nginx for Laravel
    nginx:
        image: nginx:1.25-alpine
        container_name: ticketing-nginx
        ports:
            - "8000:80"
        volumes:
            - ./backend:/var/www
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - ticketing

    # database
    mysql:
        image: mysql:9.3.0
        container_name: ticketing-mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: ticketing
            MYSQL_USER: user
            MYSQL_PASSWORD: secret
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - ticketing

volumes:
    mysql_data:
    node_modules:

networks:
    ticketing:
        driver: bridge
